[package]
name = "papajbadge-rs"
version = "0.2.136"
edition = "2021"
categories = ["embedded", "no-std"]
license = "MIT"

[features]
default = ["ble", "embassy"]
embassy = ["dep:embassy-sync"]
defmt = ["dep:defmt"]
ble = []

[dependencies]
ch58x-hal = { git="https://github.com/cr1tbit/ch58x-hal.git", features = ["default", "embassy"] }

critical-section = "1.1.2"
qingke = { version = "0.1.7", features = ["critical-section-impl"] }
qingke-rt = { version = "0.1.7", features = ["highcode"] }

fugit = "0.3.7"
nb = "1.1.0"

embedded-hal-local = { version = "1.0.0-rc.2", package = "embedded-hal" }
ledface_layout = { path = "../ledface_layout" }

defmt = { version = "1.0.1", optional = true }
spi-memory = "0.2.0"

embassy-executor = { version = "0.5.0", features = [
    "nightly",
    "arch-riscv32",
    "executor-thread",
    "integrated-timers"
] }

embassy-futures = "0.1.1"
embassy-sync = { version = "0.5.0", optional = true }
embassy-time = { version = "0.3.0" }
embassy-time-driver = { version = "0.1.0", features = ["tick-hz-32_768"] }

abc-note-stream = { git = "https://github.com/rough-rat/abc-note-stream" }

[build-dependencies]
ledface_layout = { path = "../ledface_layout" }
postcard = { version = "1.0", features = ["alloc"] }
