[package]
name = "ledface_layout"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
heapless = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-json-core = "0.5.1"
postcard = { version = "1.1", default-features = false }
